name: PR verify
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run verify
    - name: Upload coverage
      uses: qltysh/qlty-action/coverage@v1
      with:
        token: ${{secrets.QLTY_COVERAGE_TOKEN}}
        files: coverage/lcov.info
